version: '3.9'

services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Gigante24
      MYSQL_DATABASE: nextgen_db
      MYSQL_USER: nix
      MYSQL_PASSWORD: Gigante24
  # web:
  #   build: .
  #   command: python manage.py runserver127.0.0.1:8000
  #   volumes:
  #     - .:/dschoolv2_be
  #   ports:
  #     - '8000:8000'
  #   depends_on:
  #     - db

  # mongo-db:
  #   image: mongo:latest
  #   container_name: mongo-db
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: root
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - ./data/:/data/
  #   restart: unless-stopped
